### ISSUE TITLE
Can you run this app on iPhone device?

### ISSUE THREAD

**Issue by andrewwoz** [Ability42/FileManager#1]
You are using mac specific file paths. But iOS apps use only sandbox.
![screen shot 2016-11-08 at 9 13 48 pm](https://cloud.githubusercontent.com/assets/6348345/20113239/4376cf22-a5f8-11e6-83ba-682df27d5ae3.png)

**Comment by Ability42** [comment]
Yes i know that! But in simulator this works great.
It's just for test.

**Comment by andrewwoz** [comment]
so close this issue
